name: apcrcq-rnaseq-0.2
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - fastqc=0.11.9
  - python=3.7
  - trim-galore=0.6.5
  - pigz=2.4
  - star=2.7.2b
  - rsem=1.3.3
  - kraken2=2.0.9beta
  - bracken=2.6.0
  - multiqc=1.9