name: apcrcq-rnaseq-0.2 docker image build
# This builds the docker image and pushes it to GitHub packages
on:
  push:
    tags:
      - '*'

jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: apcrcq-rnaseq-0.2
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
